apiVersion: v1
kind: Service
metadata:
  name: jpr-svc
  namespace: ray
spec:
  selector:
    component: ray-head
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer