apiVersion: v1
kind: Service
metadata:
  namespace: ray
  name: rayhead-service
spec:
  selector:
    component: ray-head
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort