apiVersion: v1
kind: Service
metadata:
  name: head-svc
  namespace: ray
spec:
  selector:
    component: ray-head
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort