apiVersion: v1
kind: Service
metadata:
  namespace: ray
  name: ray-head-service
spec:
  selector:
    component: prasad-cluster-ray-head
  ports:
    - name: client-server
      port: 10001
      targetPort: 10001
    - name: dashboard
      port: 8265
      targetPort: 8265 