apiVersion: v1
kind: Service
metadata:
  namespace: ray
  name: rayml-head-svc
spec:
  selector:
    component: my-ml-cluster-ray-head
  ports:
    - name: client-server
      port: 10001
      targetPort: 10001
    - name: dashboard
      port: 8265
      targetPort: 8265 